### ISSUE TITLE
Hardware: Add a circuit to emulate the antenna deployer circuit

### ISSUE THREAD

**Issue by andrempmattos** [spacelab-ufsc/flatsat-platform2#3]
Using as reference our ISIS antenna emulator, create the hardware circuit to complete the emulation at the physical level. 

https://github.com/spacelab-ufsc/antenna-deployer-emulator

In other word, create a simple resistive load circuit to draw power from EPS that is controlled with a external MSP430 launchpad. The circuit should be something similar to:

![image](https://user-images.githubusercontent.com/25351149/105614946-8067a900-5dab-11eb-858d-1fa30f4cb0d3.png)

**Since the FlatSat2 uses a uZed for behavior emulation and test management, the launchpad could by removed and the connections/behavior adapted.**

**Comment by joaoclaudioeb** [comment]
This circuit wasn't added. Some extra pins were added to connect external circuits to the uZed. So, for now, this external circuit can be coupled using these extra pins
