### ISSUE TITLE
Fix the folder structure of the repository

### ISSUE THREAD

**Issue by mgm8** [spacelab-ufsc/flatsat-platform2#4]
The branches "dev_hardware" and "documentation" have different folder structures. This will cause conflicts in the next merge.

Recommended directory tree:

* **hardware**: Source files of the hardware project.
* **firmware** or **software**: Source files of the firmware/software project.
* **doc**: Source files of the documentation.

**Comment by YanAzer** [comment]
Changes done with the commits: e3ae5049ae0d405c1b4b067088e241b534a0ae62 and aaaa24922ab81d4490c265c40f38718ed9f68d48.
